name: pypsa-gurobi
channels:
  - gurobi
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip
  - gurobi

  # 核心依赖 - 只指定主版本
  - pypsa=0.21.3
  - atlite=0.2.14
  - dask

  # 工作流依赖 - 不指定版本
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - pyyaml
  - lxml
  - gurobi
  
  # 数据处理库 - 不指定版本
  - numpy
  - pandas=1.4.0
  - tables
  - geopandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - tqdm

  # GIS 依赖 - 最小限制
  - proj
  - fiona
  - geopy
  - cartopy
  - descartes
  - rasterio
  - pytz
  - country_converter
  - tabula-py

  # 保持在conda环境中调用ipython
  - ipython

  # 安装 poppler 以支持 fiona
  - poppler=21.09.0
  - pyogrio

  # pip 安装的包
  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - powerplantmatching>=0.4.8