# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-plot-4
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - pip

  # 核心依赖 - 只指定主版本
  - pypsa=0.27.1
  - dask

  # 工作流依赖 - 不指定版本
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - pandas=1.4.0
  - pypsa
  - matplotlib
  - geopandas
  - cartopy
  # pip 安装的包
  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - powerplantmatching>=0.4.8
