name: pypsa-gurobi
channels:
  - gurobi
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip
  - gurobi

  # 核心依赖 - 只指定主版本
  - pypsa=0.21.3
  - atlite=0.2.14
  - dask

  # 工作流依赖 - 不指定版本
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - pyyaml
  - lxml
  - gurobi
  
  # 数据处理库 - 不指定版本
  - numpy
  - pandas=1.4.0
  - tables>=3.9.2
  - python-blosc2
  - geopandas
  - xarray>=2022.12.0
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - tqdm

  # GIS 依赖 - Windows版本调整
  - proj
  - fiona>=1.8.20  # Windows下需要特定版本以上
  - geopy
  - cartopy
  - descartes
  - rasterio>=1.2.10  # Windows兼容性版本
  - pytz
  - country_converter
  - tabula-py
  - gdal  # Windows下明确添加GDAL支持

  # 保持在conda环境中调用ipython
  - ipython

  # Windows下poppler配置
  - poppler=22.04.0  # Windows兼容版本
  - pyogrio>=0.6.0  # Windows优化版本

  # pip 安装的包
  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - powerplantmatching>=0.4.8