# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-china
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip

  # 核心依赖 - 只指定主版本
  - pypsa=0.21.3
  - atlite=0.2.14
  - dask

  # 工作流依赖 - 不指定版本
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - pyyaml
  - pytables
  - lxml
  
  # 数据处理库 - 不指定版本
  - numpy
  - pandas=1.4.0
  - geopandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - tqdm

  # GIS 依赖 - 最小限制
  - proj
  - fiona
  - geopy
  - cartopy
  - descartes
  - rasterio
  - pytz
  - country_converter
  - tabula-py
  - graphviz

  # 保持在conda环境中调用ipython
  - ipython

  # 安装 poppler 以支持 fiona
  - poppler=21.09.0
  - pyogrio

  # pip 安装的包
  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - powerplantmatching>=0.4.8

# 安装指南:
# 1. 使用此文件创建环境: conda env create -f envs/environment_mac_legacy.yaml
# 2. 激活环境: conda activate pypsa-china
# 3. 检查是否需要修改_helpers.py文件中的Dict导入（如果出现相关错误） 

# # 先安装Homebrew（如果尚未安装）
# # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# # 使用Homebrew安装poppler
# brew install poppler

# # 确定安装位置
# POPPLER_PATH=$(brew --prefix poppler)

# # 在conda环境中创建所需目录
# mkdir -p /opt/anaconda3/envs/pypsa-china/lib

# # 创建符号链接到Homebrew的poppler库
# ln -s ${POPPLER_PATH}/lib/libpoppler.126.dylib /opt/anaconda3/envs/pypsa-china/lib/

# # 重新安装fiona
# conda activate pypsa-china
# conda install -c conda-forge fiona --force-reinstall 